default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: shop_user
  password: Shop36
  # socket: /opt/lampp/var/mysql/mysql.sock

development:
  <<: *default
  database: shop_development


test:
  <<: *default
  database: shop_test

production:
  <<: *default
  database: shop_production
  username: shop
  password: Shop36


# default: &default
#   adapter: mysql2
#   encoding: utf8
#   pool: 5
#   username: root
#   password: Str0ngP@ssw0rd!
#   host: localhost

# development:
#   <<: *default
#   database: tasker_development

# test:
#   <<: *default
#   database: tasker_test

# production:
#   <<: *default
#   database: tasker_production
#   username: tasker
#   password: Str0ngP@ssw0rd!